package org.agmas.noellesroles.btt;

import dev.doctor4t.wathe.api.GameMode;
import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameRoundEndComponent;
import dev.doctor4t.wathe.cca.GameTimeComponent;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.game.GameFunctions;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.text.Text;
import net.minecraft.util.Formatting;
import net.minecraft.util.Identifier;
import org.agmas.harpymodloader.Harpymodloader;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * 《终点站抵达之前》(Before the Terminal) 剧本模式主循环（Phase1 Demo，固定 6 人）。
 * DEMO-002/003/008：席位分配（教父/义警/小丑/医生/处子/列车长）+ 身份宣告（凶手/中立/外人计数）
 * + doc 结局判定（审判完成/执法落幕/旅途结束/血染快车）。
 */
public class BeforeTheTerminalGameMode extends GameMode {
    public static final Logger LOGGER = LoggerFactory.getLogger("noellesroles/btt");

    public static final Identifier ID = Identifier.of("noellesroles", "before_the_terminal");
    /** doc：到站倒计时初始 10 分钟 */
    public static final int DEFAULT_START_MINUTES = 10;
    /** doc：最少 6 人；Demo 固定 6 人（RM D5） */
    public static final int MIN_PLAYERS = 6;

    public BeforeTheTerminalGameMode() {
        super(ID, DEFAULT_START_MINUTES, MIN_PLAYERS);
    }

    @Override
    public void initializeGame(ServerWorld world, GameWorldComponent gameWorld, List<ServerPlayerEntity> players) {
        // Demo 固定 6 人（RM D5）；不符则拒绝开局
        if (players.size() != BttIdentity.DEMO_PLAYER_COUNT) {
            for (ServerPlayerEntity player : players) {
                player.sendMessage(Text.translatable("btt.start_error.exact_players", BttIdentity.DEMO_PLAYER_COUNT).formatted(Formatting.RED), false);
            }
            LOGGER.warn("[BTT] start refused: {} ready players, demo requires exactly {}.", players.size(), BttIdentity.DEMO_PLAYER_COUNT);
            GameFunctions.stopGame(world);
            return;
        }

        gameWorld.clearRoleMap();
        Map<UUID, Role> seats = BttIdentity.assignSeats(players.stream().map(ServerPlayerEntity::getUuid).toList());
        if (seats == null) {
            GameFunctions.stopGame(world);
            return;
        }
        for (ServerPlayerEntity player : players) {
            Role role = seats.get(player.getUuid());
            gameWorld.addRole(player, role);
            // 复用 NR“发初始道具”链路（列车长钥匙等），BTT 自身道具由 BttEvents 发放
            org.agmas.harpymodloader.events.ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player, role);
        }
        gameWorld.sync();

        BttGameWorldComponent btt = BttGameWorldComponent.KEY.get(world);
        btt.active = true;
        btt.lastEnding = "NONE"; // 跨局残留清理（参照 SRE finalizeGame“回合状态全清”原则）
        btt.sync();
        LOGGER.info("[BTT] round initialized: {} players seated.", players.size());

        // 身份宣告：wathe 迎新标题屏（身份名+目标） + doc 口径计数（凶手/中立/外人）聊天行
        int killers = 1;   // Demo N=6：主犯 1
        int neutrals = 1;  // 中立 1（小丑）
        int outsiders = 0; // 外人 0（N//12）
        int passengers = players.size() - killers - neutrals - outsiders;
        for (ServerPlayerEntity player : players) {
            Role role = seats.get(player.getUuid());
            int index = announcementIndex(role);
            ServerPlayNetworking.send(player, new AnnounceWelcomePayload(index, killers, passengers));
            player.sendMessage(Text.translatable("btt.reveal.header").formatted(Formatting.DARK_PURPLE, Formatting.BOLD), false);
            player.sendMessage(Text.translatable("btt.reveal.identity",
                    BttIdentity.displayName(role).withColor(role.color()), BttIdentity.factionOf(role)), false);
            player.sendMessage(Text.translatable("btt.reveal.counts", killers, neutrals, outsiders).formatted(Formatting.GRAY), false);
        }
    }

    private static int announcementIndex(Role role) {
        var text = Harpymodloader.autogeneratedAnnouncements.get(role);
        if (text == null) {
            if (role == WatheRoles.VIGILANTE) text = RoleAnnouncementTexts.VIGILANTE;
            else if (role == WatheRoles.KILLER) text = RoleAnnouncementTexts.KILLER;
            else text = RoleAnnouncementTexts.CIVILIAN;
        }
        int index = RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(text);
        return Math.max(index, 0);
    }

    @Override
    public void tickServerGameLoop(ServerWorld world, GameWorldComponent gameWorld) {
        List<ServerPlayerEntity> players = world.getPlayers();
        // 所有人离开 → 终止回合（避免无人局永久挂起）
        if (players.isEmpty()) {
            LOGGER.info("[BTT] all players left; stopping round.");
            GameFunctions.stopGame(world);
            return;
        }

        int aliveMurderers = 0;
        int alivePassengers = 0;
        int totalPassengers = 0;
        boolean anySeats = false;
        for (ServerPlayerEntity player : players) {
            Role role = gameWorld.getRole(player);
            if (role == null) continue;
            anySeats = true;
            if (role.isInnocent()) {
                totalPassengers++;
                if (GameFunctions.isPlayerAliveAndSurvival(player)) alivePassengers++;
            } else if (role.canUseKiller()) {
                if (GameFunctions.isPlayerAliveAndSurvival(player)) aliveMurderers++;
            }
        }
        if (!anySeats) return; // 防御：尚无座位（不应发生）

        int deadPassengers = totalPassengers - alivePassengers;
        boolean stationReached = !GameTimeComponent.KEY.get(world).hasTime();

        BttEndings.Ending ending = BttEndings.decide(aliveMurderers, alivePassengers, deadPassengers, totalPassengers, stationReached);
        if (ending != BttEndings.Ending.NONE && gameWorld.getGameStatus() == GameWorldComponent.GameStatus.ACTIVE) {
            LOGGER.info("[BTT] ending decided: {} (aliveM={} aliveP={} deadP={} station={})",
                    ending, aliveMurderers, alivePassengers, deadPassengers, stationReached);
            // doc 结局写入同步组件：客户端 BttEndScreenMixin 直接替换 wathe 结束覆盖层文本（不在聊天框输出）
            BttGameWorldComponent btt = BttGameWorldComponent.KEY.get(world);
            btt.lastEnding = ending.name();
            btt.sync();
            GameRoundEndComponent.KEY.get(world).setRoundEndData(new ArrayList<>(players), BttEndings.winStatusOf(ending));
            GameFunctions.stopGame(world);
        }
    }

    @Override
    public void finalizeGame(ServerWorld world, GameWorldComponent gameWorld) {
        // wathe GameFunctions.finalizeGame 已完成：清角色/重置玩家/清尸体/INACTIVE。
        BttGameWorldComponent btt = BttGameWorldComponent.KEY.get(world);
        btt.active = false;
        btt.sync();
    }
}
