package org.agmas.noellesroles.mixin.btt;

import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.cca.GameRoundEndComponent;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.game.GameFunctions;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.world.World;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.noellesroles.btt.BttIdentity;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Mutable;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * BTT 结局数据（NRS 式，C-022）：setRoundEndData 不再按阵营三分组，
 * 每玩家 RoundEndData.role = 其**真实身份**的 per-role 宣告条目
 * （HML autogeneratedAnnouncements：键 announcement.role.noellesroles.<path>，双方侧一致注册）。
 * 实现：TAIL 重建列表（record 不可变；@At("NEW") 对 record 实例化扫描 0 目标故弃用）。
 * 取代原 BttRoundEndMixin（义警列分类随之作废——不再分列）。
 * didWin 保留阵营语义（胜负音效与展示列解耦）：KILLERS→凶手、PASSENGERS/TIME→乘客、NONE(含 THIEF_WIN)→false。
 */
@Mixin(GameRoundEndComponent.class)
public abstract class BttRoundEndRoleMixin {

    @Shadow @Final private World world;
    @Shadow @Final @Mutable private List<GameRoundEndComponent.RoundEndData> players;

    // per-role 写入已迁出（C-030）：HML 宣告条目 index 高达 70+，写入世界存档后重进世界时
    // HML 注册尚未发生（SERVER_STARTED 之后）→ ROLE_ANNOUNCEMENT_TEXTS 只有 5 条 → IndexOutOfBounds 读档崩。
    // 结局职业数据改存 btt_game.endRoles（本组件回归 wathe 原生三分组，index 恒 0-4）。


    @Inject(method = "didWin(Ljava/util/UUID;)Z", at = @At("HEAD"), cancellable = true)
    private void bttDidWin(UUID uuid, CallbackInfoReturnable<Boolean> cir) {
        if (!BttIdentity.isBttMode(world)) return;
        // fork 口径：胜负=服务端下发的 btt_game.winners（覆盖全部结局，音效与结局分组一致）
        String winners = org.agmas.noellesroles.btt.BttGameWorldComponent.KEY.get(world).winners;
        cir.setReturnValue(java.util.Arrays.stream(winners.split(",")).anyMatch(uuid.toString()::equals));
    }
}
